name: PeeVeePeeArena
main: no.runsafe.peeveepeearena.PeeVeePeeArena
version: 1.0.@BUILD@
author: Kruithne
depend: [RunsafeMailbox, RunsafeWorldGuardBridge]
description:
commands:
  pvp:
    description: PvP related commands
